<xs:element name="Person">
  <xs:complexType name="Person">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="age" type="xs:positiveInteger"/>
    </xs:sequence>
  </xs:complexType>
</xs:element

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="recipeCollection">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="recipe" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="ingredients">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ingredient" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="instructions">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="instruction" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="cookingTime" type="xs:string"/>
							<xs:element name="servings" type="xs:positiveInteger"/>
							<xs:element name="dietaryInfo" type="xs:string" minOccurs="0" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>